# Generated by Django 3.1.2 on 2020-10-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starrating',
            old_name='start_rating',
            new_name='star_rating',
        ),
    ]
