# Generated by Django 3.1.2 on 2020-10-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=5000)),
                ('cast_as', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cast',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genres')),
            ],
            options={
                'db_table': 'movie_genres',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('premier', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('run_time', models.CharField(max_length=10)),
                ('poster_url', models.URLField()),
                ('in_theaters', models.BooleanField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='MovieVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='MovieTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.tags')),
            ],
            options={
                'db_table': 'movie_tags',
            },
        ),
        migrations.CreateModel(
            name='MovieServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.services')),
            ],
            options={
                'db_table': 'movie_services',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='casting',
            field=models.ManyToManyField(related_name='people', through='movie.Cast', to='movie.People'),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(related_name='genres', through='movie.MovieGenres', to='movie.Genres'),
        ),
        migrations.AddField(
            model_name='movies',
            name='service',
            field=models.ManyToManyField(related_name='services', through='movie.MovieServices', to='movie.Services'),
        ),
        migrations.AddField(
            model_name='movies',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='movie.MovieTags', to='movie.Tags'),
        ),
        migrations.CreateModel(
            name='MoviePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.AddField(
            model_name='moviegenres',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AddField(
            model_name='cast',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.people'),
        ),
    ]
