# Generated by Django 3.1.2 on 2020-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201021_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='casting',
            field=models.ManyToManyField(related_name='people', through='movie.Cast', to='movie.People'),
        ),
    ]
