# Generated by Django 3.1.2 on 2020-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201021_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='premier',
            field=models.CharField(max_length=100),
        ),
    ]
