# Generated by Django 3.1.2 on 2020-10-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201021_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='icon',
            new_name='icon_url',
        ),
    ]
