# Generated by Django 3.1.2 on 2020-10-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20201022_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
