# Generated by Django 3.1.2 on 2020-10-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201022_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='avatar_url',
            field=models.CharField(max_length=200),
        ),
    ]
