# Generated by Django 3.1.2 on 2020-10-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20201022_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='premier',
            new_name='premier_date',
        ),
    ]
