# Generated by Django 3.1.2 on 2020-10-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20201022_0428'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
