# Generated by Django 3.1.2 on 2020-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20201022_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(default='왓챠디피아를 만난 왓챠앤칠 백둥이들인 창공과 예징은 거대한 데이터베이스를 자랑하는 왓챠디피아를 보고 고개를 젓는다. “이거 완전 데이터 변태들이네..” 왜 이렇게나 데이터를 만든 것인지 아무도 모른다. 혼란에 빠진 창공과 예징, 그래도 그들만의 프로젝트를 위해 다른 별에 살고 있는 프둥이들을 만나 왓챠디피아에 한 발씩 다가서고, 프로젝트 성공을 위한 그들만의 사투가 시작된다. 변태 데이터 왓챠디피아.. 너를 정복하리라..', max_length=5000),
            preserve_default=False,
        ),
    ]
