# Generated by Django 3.1.2 on 2020-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='coverpic_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1508633069371-a735f885a1c7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80', max_length=200),
            preserve_default=False,
        ),
    ]
