# Generated by Django 3.1.2 on 2020-10-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movies_coverpic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='premier_date',
            field=models.DateField(max_length=100),
        ),
    ]
