# Generated by Django 3.1.2 on 2020-10-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20201027_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='coverpic_url',
            field=models.URLField(),
        ),
    ]
