# Generated by Django 3.1.2 on 2020-10-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20201027_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(max_length=1000),
        ),
    ]
